theme: jekyll-theme-cayman
title: First, solve the problem. Then, write the code
overview: I’ve been working with software since the days of Windows 3.1 and DOS. Remember Dial-up modems, Netscape, Doom on 3.5" floppy disks? I do.
These days I do a lot of User journey planning, Automation, and Dev Ops. My current passions are Machine learning, Structured Data, and API integration.
