theme: jekyll-theme-cayman
title: "Disruptor.\n
Innovator.\n
Creator. Doer."
overview: "Digital Development Manager, Digital Product Development, Process Automation, Data Compliance, ERP/ CRM System Configuration."
hero: /assets/images/profile-lg.webp
hero2: /assets/images/PR2.jpg
logo: /assets/images/prand-logo.svg
github: https://github.com/prandle
linkedin: https://www.linkedin.com/in/paulrandle
location: 8 Springfield Road, Upper Poppleton, York. YO26 6JW
twitterUrl: https://twitter.com/prand1
tel: 0113 815 4355
email: mailto:mail@paulrandle.co.uk
markdown: GFM
