theme: jekyll-theme-cayman
title: "Disruptor.\n
Innovator.\n
Creator. Doer."
overview: "I’ve been working with software since the days of Windows 3.1 and DOS. \n
Remember Dial-up modems, Netscape, Doom on 3.5'' floppy disks? I do. \n
These days I do a lot of User journey planning, Automation, and Dev Ops. \n
My current passions are Machine learning, Structured Data, and API integration."
hero: /assets/images/PR2.jpg
